名称: 刷课
 
在：
  推：
: [主要]
  #是否开始每天8点定时刷课，若要开启请把下面两行备注去掉
  ＃ 浙江：
  # - cron:“0 8 * * *”
    
职位：
  开始：
    连续运行           : ubuntu-latest # 在最新版本的 Ubuntu 网络环境下运行
    步骤         : # 要执行的步骤
      -名称：复制代码
        用途：actions/checkout@v3         #用于将github代码仓库的代码拷贝到工作目录中
 
      - name :设置python环境
        使用     : actions/setup-python@v2 #用于设置Python环境，它允许你指定要在工作环境中使用的Python版本
        和：
          python版本：'3.9'    # 选择使用的Python版本
 
      -名称：安装依赖包
        运行：| # 安装依赖包
          pip install -r ./requirements.txt
          
      
      -名称：运行main.py
        run : python main.py -u 15753397535 -p L15753397535 -l 245347699 #课程id，默认为心理课的
